eventbrite/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('',views.ListEvents.as_view(), name="all"),
    path("new/",views.CreateEvent.as_view(),name="create"),
    path("posts/in/<slug>/",views.SingleEvent.as_view(),name="single"),
    path("join/<slug>/",views.LikeEvent.as_view(),name="like"),
    path("leave/<slug>/",views.UnlikeEvent.as_view(),name="unlike"),
    path("myevents",views.UserEvents.as_view(),name="userevents"),
    path("likedevents/",views.LikedEvents.as_view(),name="likedevents"),
]

#urls which routed to the "api" app will be directed to this file to move further

eventbrite/eventbrite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('front_end/', include('front_end.urls', namespace='front_end')),
    path('front_end/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('api/',include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Main urls.py file where routing starts and continues the route to connected apps

eventbrite/front_end/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'front_end'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="front_end/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.Signup.as_view(), name='signup'),
]
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'front_end'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="front_end/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.Signup.as_view(), name='signup'),
]

#urls mainly for front end i.e signup,login ans logout are routed here

eventbrite/api/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
from front_end.models import User


#creating user model by importing get_user_model from django
from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

# A DB table is been created for events:
class Event(models.Model):
    user = models.ForeignKey(User,related_name='events',on_delete=models.CASCADE)
    name = models.CharField(max_length=256,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    date = models.DateField()
    time = models.TimeField()
    location = models.TextField(default='')
    image = models.ImageField(upload_to='event_picture/',blank=True)
    likes = models.ManyToManyField(User,through='EventLikes')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('api:single', kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']
        unique_together = ['user','name']

#A DB table for likedevents by the user:
class EventLikes(models.Model):
    event = models.ForeignKey(Event,related_name='event_likes',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_likes',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('event','user')

eventbrite/front_end/models.py
from django.db import models
from django.contrib import auth
from django.utils import timezone

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

eventbrite/front_end/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class CreateUserForm(UserCreationForm):

    class Meta:
        fields = ('username','email','password1','password2')
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label='Display Name'
        self.fields['email'].label='Email Address'

eventbrite/api/views.py
from django.contrib import messages
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.views import generic
from api.models import Event,EventLikes
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()

#view for creating events by the user:
class CreateEvent(LoginRequiredMixin,generic.CreateView):
    fields = ['name','description','date','time','location','image']
    model = Event

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        if 'image' in self.request.FILES: #saving the image by a perticular user creating the event
            self.object.image = self.request.FILES['image']
        self.object.save()
        return super().form_valid(form)

#Detail view for a single event:
class SingleEvent(generic.DetailView):
    model = Event

#View for list of events:
class ListEvents(generic.ListView):
    model = Event

#Like event:
class LikeEvent(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse("api:single",kwargs={"slug": self.kwargs.get("slug")})
    def get(self, request, *args, **kwargs):
        event = get_object_or_404(Event,slug=self.kwargs.get("slug"))
        try:
            EventLikes.objects.create(user=self.request.user,event=event)
        except IntegrityError:
            messages.warning(self.request,"Already liked!")
        else:
            messages.success(self.request,"Added to liked events!")
        return super().get(request, *args, **kwargs)

#Unlike event:
class UnlikeEvent(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse("api:single",kwargs={"slug": self.kwargs.get("slug")})
    def get(self, request, *args, **kwargs):
        try:
            event_likes = models.EventLikes.objects.filter(user=self.request.user,event__slug=self.kwargs.get("slug")).get()
        except models.EventLikes.DoesNotExist:
            messages.warning(self.request,"You never liked this event!")
        else:
            event_likes.delete()
            messages.success(self.request,"Removed from liked events!")
        return super().get(request, *args, **kwargs)

#User created events:
class UserEvents(LoginRequiredMixin, generic.ListView):
    model = models.Event
    template_name = "api/user_event_list.html"
    context_object_name = 'events'
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)

#User liked events:
class LikedEvents(LoginRequiredMixin, generic.ListView):
    model = models.EventLikes
    template_name = "api/liked_events.html"
    context_object_name = 'events'
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)

eventbrite/eventbrite/views.py
from django.views.generic import TemplateView
#template view for test.html,thanks.html and index.html

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = 'index.html'

eventbrite/front_end/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms

#a signup view
# Login and logout have been taken care in settings.py with redirect url

class Signup(CreateView):
    form_class = forms.CreateUserForm
    success_url = reverse_lazy('login')
    template_name = 'front_end/signup.html'

eventbrite/api/templates/api/event_base.html
{% extends "base.html" %}
{% comment %} HTML File which acts as a base for all other event related files which can be extended in other files {% endcomment %}

{% block content %}
<div class="container">
  <div class="row">
    {% block preevent %}{% endblock %}
    {% block event_content %}{% endblock %}
    {% block postevent %}{% endblock %}
  </div>
</div>
{% endblock %}

eventbrite/api/templates/api/event_detail.html
{% extends "api/event_base.html" %}

{% comment %} The event post details as a grid view where image and discription are divided in the ratio 4:8 {% endcomment %}
{% block preevent %}
<div class="container">
  <div class="card mb-3">
    <div class="row g-0">
      <div class="col-md-4">
        <img class="card-img img-fluid rounded-start" src={{ event.image.url }} alt="Error404" >

      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h2 class="card-title">{{event.name}}</h2>
            <p class="mb-1"><span class="fa fa-calendar"></span> {{ event.date }}</p>
            <p class="mb-1"><span class="fa fa-clock-o"></span> {{ event.time }}</p>
            <p class="mb-1"><span class="fa fa-map-marker"></span> {{ event.location }}</p>
            <h4 class="mb-1">{{ event.description|safe }}</h4>
            <div class="d-flex w-40 justify-content-between">
              <h4><small class="text-muted"><span class="badge badge-secondary">
                 {{ event.likes.count }}</span> like{{ event.likes.count|pluralize }}</small></h4>
            </div>
            {% if user in event.likes.all %}
              <a href="{% url 'api:unlike' slug=event.slug %}" class="btn btn-lg btn-warning"><span class="fa fa-heart"></span> UnLike</a>
            {% else %}
              <a href="{% url 'api:like' slug=event.slug %}" class="btn btn-lg btn-warning"><span class="fa fa-heart-o"></span> Like</a>
            {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
          
{% endblock %}

eventbrite/api/templates/api/event_form.html
{% extends "api/event_base.html" %}
{% load bootstrap4 %}
{% comment %} A bootstrap form for creating an Event {% endcomment %}
{% block event_content %}
<div class="container">
  <h4>Create A New Event</h4>
  <form method="POST" action="{% url 'api:create' %}" id="eventForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
    {% buttons %}
  		<button type="submit" class="btn btn-primary btn-large">Create</button>
  	{% endbuttons %}
  </form>
</div>
{% endblock %}

eventbrite/api/templates/api/event_list.html
{% extends "api/event_base.html" %}
{% block preevent %}

{% comment %} An option to create a event will be given on left side and the All events are listed on right side which is divided
in the ratio 3:9 {% endcomment %}
<div class="col-md-3">

  <div class="content">

    {% if user.is_authenticated %}
      <h2>Welcome back! {{user.username}}</h2>
    {% endif %}
  </div>
  {% if user.is_authenticated %}
    <a href="{% url 'api:create' %}" class="btn btn-md btn-fill btn-default">
      <span class="fa fa-plus"><span> </span>Create New Event</span>
    </a>
  {% endif %}

</div>

{% endblock %}

{% block event_content %}
  <div class="col-md-9">
    <div class="list-group">
      {% for event in object_list %}
  		  <a href="{% url 'api:single' slug=event.slug %}"
  		     class="list-group-item list-group-item-action flex-column align-items-start">
               <div class="container">
                <div class="card mb-3">
                  <div class="row g-0">
                    <div class="col-md-4">
                      <img class="card-img img-fluid rounded-start" src={{ event.image.url }} alt="Error404" >
              
                    </div>
                    <div class="col-md-8">
                      <div class="card-body">
                        <h2 class="card-title">{{event.name}}</h2>
                          <p class="mb-1"><span class="fa fa-calendar"></span> {{ event.date }}</p>
                          <p class="mb-1"><span class="fa fa-clock-o"></span> {{ event.time }}</p>
                          <p class="mb-1"><span class="fa fa-map-marker"></span> {{ event.location }}</p>
                          <h4 class="mb-1">{{ event.description|safe }}</h4>
                          <div class="d-flex w-40 justify-content-between">
                            <h4><small class="text-muted"><span class="badge badge-secondary">
                               {{ event.likes.count }}</span> like{{ event.likes.count|pluralize }}</small></h4>
                          </div>
                      </div>
                    </div>
                </div>
              </div>
            </div>

  		  </a>
  		{% endfor %}
    </div>
  </div>
{% endblock %}

eventbrite/api/templates/api/liked_events.html
{% extends "api/event_base.html" %}

{% block preevent %}
<div class="col-md-4">
	<h2>Liked events by {{ user.username }}:</h2>
</div>
{% endblock %}

{% comment %} Listing the events which are liked by a perticular user {% endcomment %}
{% block event_content %}
<div class="col-md-8">
	<div class="list-group">
  	{% if events %}
	      {% for event in events %}
					<a href="{% url 'api:single' slug=event.event.slug %}"
						 class="list-group-item list-group-item-action flex-column align-items-start">
						 <h2 class="mb-1">{{ event.event.name }}</h2>
						 <p class="mb-1"><span class="fa fa-calendar"> {{ event.event.date }} {{ event.event.time }}</p>
						 <p class="mb-1"><span class="fa fa-map-marker"> {{ event.event.location }}</p>
							 <div class="d-flex w-40 justify-content-between">
									<small class="text-muted"><span class="badge badge-secondary">
										 {{ event.event.likes.count }}</span> like{{ event.event.likes.count|pluralize }}</small>
									<span></span><span></span>
							 </div>
					</a>
	      {% endfor %}
  	{% else %}
    	<h2>You have not liked any events yet!</h2>
  	{% endif %}
	</div>
</div>
{% endblock %}

eventbrite/api/templates/api/user_event_list.html
{% extends "api/event_base.html" %}

{% comment %} User specific events are listed using this file {% endcomment %}
{% block preevent %}
<div class="col-md-4">
	<h2>Events by {{ user.username }}:</h2>
</div>
{% endblock %}

{% block event_content %}
<div class="col-md-8">
	<div class="list-group">
  	{% if events %}
	      {% for event in events %}
					<a href="{% url 'api:single' slug=event.slug %}"
						 class="list-group-item list-group-item-action flex-column align-items-start">
						 <h2 class="mb-1">{{ event.name }}</h2>
						 <p class="mb-1"><span class="fa fa-calendar"> {{ event.date }} {{ event.time }}</p>
						 <p class="mb-1"><span class="fa fa-map-marker"> {{ event.location }}</p>
							 <div class="d-flex w-40 justify-content-between">
									<small class="text-muted"><span class="badge badge-secondary">
										 {{ event.likes.count }}</span> like{{ event.likes.count|pluralize }}</small>
									<span></span><span></span>
							 </div>
					</a>
	      {% endfor %}
  	{% else %}
    	<h2>You have not created any events yet!</h2>
  	{% endif %}
	</div>
</div>
{% endblock %}

eventbrite/front_end/templates/front_end/login.html
{% extends "base.html" %}

{% comment %} Bootstrap4 form for login {% endcomment %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
  <h1>Login</h1>
  <form method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Login</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

eventbrite/front_end/templates/front_end/signup.html
{% extends "base.html" %}
{% comment %} these id's are accessed in app.js {% endcomment %}
<div id="main"> 
    <div id="app"></div>
</div>

{% comment %} A Bootstrap4 form for registration {% endcomment %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
  <h1>Sign Up</h1>
  <form method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Register</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

eventbrite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Eventbrite</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&display=swap" rel="stylesheet">

    <!-- CSS Linkage -->
    <link rel="stylesheet" href="{% static 'css/master.css' %}">

  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-xl mynav" role="navigation" id="navbar">
          <div class="navbar-nav align-items-center">
            <a class="navbar-brand mynav" href="{% url 'home' %}">Eventbrite</a>
          </div>
          <div class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'api:all' %}" class="btn btn-simple">Explore Events</a>
              <a class="nav-item nav-link" href="{% url 'api:userevents' %}" class="btn btn-simple">My Events</a>
              <a class="nav-item nav-link" href="{% url 'api:likedevents' %}" class="btn btn-simple">Liked Events</a>
              <a class="nav-item nav-link" href="{% url 'front_end:logout' %}" class="btn btn-simple">Log out</a>
            {% else %}
              <a class="nav-item nav-link" href="{% url 'api:all' %}" class="btn btn-simple">Explore Events</a>
              <a class="nav-item nav-link" href="{% url 'front_end:login' %}" class="btn btn-simple">Log in</a>
              <a class="nav-item nav-link" href="{% url 'front_end:signup' %}" class="btn btn-simple">Register</a>
            {% endif %}
          </div>
      </nav>

    <!-- </nav> -->



    <div class="container">

      {% block content %}

      {% endblock %}

    </div>


  <canvas id="canvas"></canvas>

   <script src="{% static "front_end/main.js" %}" type="text/javascript"></script>
   <script src="{% static "ignis/js/event.js" %}" type="text/javascript"></script>

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>


</html>

eventbrite/templates/index.html
{% extends "base.html" %}
{% block content %}

<!-- carousel -->
<div id="demo" class="carousel slide" data-ride="carousel">

<!-- Indicators -->
<ul class="carousel-indicators">
  <li data-target="#demo" data-slide-to="0" class="active"></li>
  <li data-target="#demo" data-slide-to="1"></li>
  <li data-target="#demo" data-slide-to="2"></li>
  <li data-target="#demo" data-slide-to="3"></li>
</ul>

<!-- The slideshow -->
<div class="carousel-inner">
  <div class="carousel-item active">
    <img src="static/images/index.jpg" class="img-fluid" alt="Error404">
  </div>
  <div class="carousel-item">
    <img src="static/images/index1.jpg" class="img-fluid" alt="Error404">
  </div>

<!-- Left and right controls -->
<a class="carousel-control-prev" href="#demo" data-slide="prev">
  <span class="carousel-control-prev-icon"></span>
</a>
<a class="carousel-control-next" href="#demo" data-slide="next">
  <span class="carousel-control-next-icon"></span>
</a>

</div>

<!-- The content -->
  <div class="container thecontent">
    <h1 class="theheading">Welcome To Eventbrite!</h1>
    <p class="thepara">Eventbrite is an American event management and ticketing website. The service allows users to browse, create, and promote local events. The service charges a fee to event organizers in exchange for online ticketing services, unless the event is free. Launched in 2006 and headquartered in San Francisco, Eventbrite opened their first international office in the United Kingdom in 2012. The company has local offices in Nashville, London, Cork, Amsterdam, Dublin, Berlin, Melbourne, Mendoza, Madrid, and São Paulo. The company went public on the New York Stock Exchange on September 20, 2018 under the ticker symbol EB.</p>
  </div>
{% endblock %}

eventbrite/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron container">
  <h1 class="theheading">Log In successfull!</h1>
</div>
{% endblock %}

eventbrite/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron container">
  <h1 class="theheading">Thank You! Come Back Soon!</h1>
</div>
{% endblock %}